Services and controllers
DorWolfgorAcademy/Epicure-back pull request #2
Opened 2022-06-21 06:57 UTC by DorWolfgorAcademy

Chef and Restaurant are done.

2022-06-21 07:44 UTC, omrip2 requested changes

2022-06-21 07:44 UTC, omrip2 commented on src/main/java/com/controller/ChefController.java
> +    List<Chef> all(@RequestParam(name = "sort-by") String sortBy) {
The sort by can be an enum

2022-06-21 07:44 UTC, omrip2 commented on src/main/java/com/controller/HomeController.java
> +        return "home";
Add TODO comment for all the unimplemented endpoints so you won't forget to implement it
The opposite from forgetting is writing

2022-06-21 07:44 UTC, omrip2 commented on src/main/java/com/controller/RestaurantController.java
> +    public RestaurantController(RestaurantService restaurantService) {
Add validations to all endpoints

2022-06-21 07:44 UTC, omrip2 commented on src/main/java/com/controller/RestaurantController.java
> +                         @RequestParam(required = false) Double longitude,
Add default values to all params

2022-06-21 07:44 UTC, omrip2 commented on src/main/java/com/service/RestaurantService.java
> +        restaurants = filterRestaurants(restaurants,minDishPrice,maxDishPrice,rating,distance,latitude,longitude);
The filter should be in the db and not in the service

2022-06-21 08:47 UTC, DorWolfgorAcademy commented on src/main/java/com/controller/HomeController.java
> +        return "home";
fixed

2022-06-21 08:56 UTC, DorWolfgorAcademy commented on src/main/java/com/controller/ChefController.java
> +    List<Chef> all(@RequestParam(name = "sort-by") String sortBy) {
fixed

2022-06-23 08:23 UTC, DorWolfgorAcademy commented on src/main/java/com/service/RestaurantService.java
> +        restaurants = filterRestaurants(restaurants,minDishPrice,maxDishPrice,rating,distance,latitude,longitude);
fixed

2022-06-23 08:23 UTC, DorWolfgorAcademy commented on src/main/java/com/controller/RestaurantController.java
> +                         @RequestParam(required = false) Double longitude,
fixed

2022-06-23 08:24 UTC, DorWolfgorAcademy commented on src/main/java/com/controller/RestaurantController.java
> +    public RestaurantController(RestaurantService restaurantService) {
fixed

2022-06-26 10:01 UTC, omrip2 approved these changes

2022-06-28 06:48 UTC, merged