Service test restaurant
DorWolfgorAcademy/Epicure-back pull request #4
Opened 2022-06-26 07:30 UTC by DorWolfgorAcademy

2022-07-05 08:05 UTC, omrip2 requested changes

2022-07-05 08:05 UTC, omrip2 commented on src/test/java/com/service/RestaurantServiceTest.java
> +        Chef chef1 = new Chef("dor1","chef 1", "url1",0,new Date(2013, Calendar.FEBRUARY,13));
Please move all the static data to a separate class

2022-07-05 08:05 UTC, omrip2 commented on src/test/java/com/service/RestaurantServiceTest.java
> +    void checkTest() {
Delete

2022-07-05 08:05 UTC, omrip2 commented on src/test/java/com/service/RestaurantServiceTest.java
> +    void getAll() {
change the name of this function to be something more self explanatory such as getAllResturants

2022-07-10 11:55 UTC, omrip2 commented on src/main/java/com/controller/HomeController.java
> +    public String  getHomePage(){
Add todo comment so you want forget it later

2022-07-10 12:00 UTC, omrip2 approved these changes

2022-07-10 13:47 UTC, DorWolfgorAcademy commented on src/test/java/com/service/RestaurantServiceTest.java
> +        assertEquals(restaurantList.get(0), service.add(restaurantList.get(0)));
fixed

2022-07-10 13:47 UTC, DorWolfgorAcademy commented on src/test/java/com/service/RestaurantServiceTest.java
> +        Chef chef1 = new Chef("dor1","chef 1", "url1",0,new Date(2013, Calendar.FEBRUARY,13));
fixed

2022-07-10 13:47 UTC, DorWolfgorAcademy commented on src/test/java/com/service/RestaurantServiceTest.java
> +    void checkTest() {
fixed

2022-07-10 13:47 UTC, DorWolfgorAcademy commented on src/test/java/com/service/RestaurantServiceTest.java
> +    void getAll() {
fixed

2022-07-10 13:48 UTC, DorWolfgorAcademy commented on src/main/java/com/controller/HomeController.java
> +    public String  getHomePage(){
fixed

2022-07-10 14:22 UTC, merged